/**
 * File generated from the fore::org::fore::primitifs::IPlane uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package org.fore.primitifs;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of IPlane.
 */
public class IPlane {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public IPlane() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method setWidth.
     * @param radius 
     */
    public void setWidth(float radius) {
    	// Start of user code for method setWidth
    	// End of user code
    }
     
    /**
     * Description of the method getWidth.
     * @return 
     */
    public float getWidth() {
    	// Start of user code for method getWidth
    	float getWidth = 0.0f;
    	return getWidth;
    	// End of user code
    }
     
    /**
     * Description of the method setHeight.
     * @param radius 
     */
    public void setHeight(float radius) {
    	// Start of user code for method setHeight
    	// End of user code
    }
     
    /**
     * Description of the method getHeight.
     * @return 
     */
    public float getHeight() {
    	// Start of user code for method getHeight
    	float getHeight = 0.0f;
    	return getHeight;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
