/**
 * File generated from the fore::org::fore::primitifs::ISphere uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package org.fore.primitifs;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ISphere.
 */
public class ISphere {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public ISphere() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method setRadius.
     * @param radius 
     */
    public void setRadius(float radius) {
    	// Start of user code for method setRadius
    	// End of user code
    }
     
    /**
     * Description of the method getRadius.
     * @return 
     */
    public float getRadius() {
    	// Start of user code for method getRadius
    	float getRadius = 0.0f;
    	return getRadius;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
